# Generated by Django 3.1.1 on 2020-09-09 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='employees.department'),
            preserve_default=False,
        ),
    ]
